### PR TITLE
Added support to play audio files from assets

### PR DESCRIPTION
**Pull request by Alvarocda**
I managed to get the library to play audio files from the assets folder.
I will try to make a brief explanation of how I did this.
When the user passes an InputAssetNode object in the open verb, it will create a temporary copy of the file in the application's temporary folder.
I created a verb called _startPlayerFromAsset, in this verb, I basically copied what the _startPlayerFromUri verb does but I made some adjustments to work with the asset's temporary file.

If there are any suggestions for improvement, you can tell me that I will try to improve

### CODE REVIEW

**Comment by Larpoux** [comment]
Hi my Brazilian friend 😄 ,

I just looked to your Pull Request, and for me it is good 👍 

Just a few remarks : 
- You load the asset in memory, write it to a temporary file, and _startPlayerFromURI().  It would be simpler and faster to load the asset in memory, and simply _startPlayerFromBuffer()
- Your temporary file is a "xxxx.wav", but the asset can be "xxxx.opus", "xxxx.mp3", etc...

**Comment by Alvarocda** [comment]
> Hi my Brazilian friend 😄 ,
> 
> I just looked to your Pull Request, and for me it is good 👍
> 
> Just a few remarks :
> 
> * You load the asset in memory, write it to a temporary file, and _startPlayerFromURI().  It would be simpler and faster to load the asset in memory, and simply _startPlayerFromBuffer()
> * Your temporary file is a "xxxx.wav", but the asset can be "xxxx.opus", "xxxx.mp3", etc...

Ok, I will make these adjustments 😃

**Comment by Alvarocda** [comment]
> Hi my Brazilian friend 😄 ,
> 
> I just looked to your Pull Request, and for me it is good 👍
> 
> Just a few remarks :
> 
> * You load the asset in memory, write it to a temporary file, and _startPlayerFromURI().  It would be simpler and faster to load the asset in memory, and simply _startPlayerFromBuffer()
> * Your temporary file is a "xxxx.wav", but the asset can be "xxxx.opus", "xxxx.mp3", etc...

Fixed 😆

**Comment by Larpoux** [comment]
Thank you so much @Alvarocda for your contribution. We appreciate.

**Comment by Alvarocda** [comment]
Hey, i'm trying to run the example in tau10/tau_sound/example to add a exemple of starting the player from asset
But when i try to run, it gives me the following error:



```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\dev\tau10\tau_sound\example\android\app\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 936ms
Exception: Gradle task assembleDebug failed with exit code 1
```

Other apps works just fine.

```
C:\>java --version
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
```


```
C:\>javac --version
javac 11.0.10
```

Do you have any clues of what is causing this?

**Comment by Larpoux** [comment]
You can try in Android Studio : 

File > Project Structure ...

Click "JDK location was moved to Gradle Settings"

And there you can enter your Java location.

Note : Android Studio move all the menus from version to version, and is not always same on MacOS, Windows and Linux.
Perhaps you will have to find yourself where is this F***g menu

**Pull request merged**
